version: '3'
services:
  scorekeeper:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
      args:
        - APACHE_VERSION=${APACHE_VERSION}
    image: '${IMAGE_NAME}'
    ports:
      - "${PORT}:80"